export const defaultBackgroundColor = '#F5F5F5'
export const defaultBorderColor = '#D1D1D1'
export const defaultTextColor = '#000'
export const defaultShadowColor = 'rgba(0, 0, 0, 0.1)'
export const defaultIconColor = '#333'
